# Generated by Django 4.2.6 on 2023-10-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shirts',
            new_name='Shirt',
        ),
    ]
