# Generated by Django 4.2.6 on 2023-10-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shirt_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
