# Generated by Django 4.2.6 on 2023-10-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
