# Generated by Django 4.2.6 on 2023-10-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
    ]
