# Generated by Django 4.2.6 on 2023-10-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='username',
            new_name='name',
        ),
    ]
